export const siteConfig = {
  name: "Priyanka Panjabi",
  title: "Senior Frontend Engineer",
  tagline: "📍 Calgary, Canada · Canadian PR · Open to work in Canada & US",
  description:
    "Portfolio of Priyanka Panjabi — Senior Frontend Engineer specializing in React and TypeScript",
  accentColor: "#2563eb",
  social: {
    email: "priyanka.panjabi88@gmail.com",
    linkedin: "https://www.linkedin.com/in/priyanka-panjabi-84496112b/",
    github: "https://github.com/Priyanka-Panjabi",
  },
  aboutMe: [
    "🚀 8+ years building React & TypeScript applications at 1M+ user scale.",
    "⚡ Delivered ~40–50% performance improvements across enterprise healthcare platforms at Optum (UnitedHealth Group).",
    "🏗️ Architected a shared component library adopted by 10+ teams at Thomson Reuters.",
    "💼 Experience spanning healthcare, enterprise SaaS, and logistics at Wipro and Reliance Jio.",
    "📍 Based in Calgary, Canada — eligible to work in Canada and the US.",
    "🎯 Seeking Senior and Tech Lead roles where I can own complex frontend systems and raise the engineering bar.",
  ],
  skills: [
    "React.js",
    "Next.js",
    "TypeScript",
    "JavaScript (ES6+)",
    "Redux / Redux-Saga",
    "Context API",
    "Node.js",
    "REST APIs",
    "HTML5 / CSS3",
    "Material UI",
    "Tailwind CSS",
    "SCSS / Sass",
    "Jest / React Testing Library",
    "WebdriverIO (WDIO)",
    "GitHub Actions / CI/CD",
    "Webpack",
    "Accessibility (a11y)",
    "Performance Optimization",
    "Agile / Scrum",
  ],
  projects: [],
  experience: [
    {
      company: "Wipro Limited · Optum (UnitedHealth Group)",
      title: "Senior Software Engineer, Frontend",
      dateRange: "Dec 2021 – Dec 2025",
      bullets: [
        "Engineered core React + Redux-Saga features for a healthcare platform serving 1M+ users, enabling critical clinical and operational workflows across UnitedHealth Group.",
        "Drove a ~40–50% reduction in page load times by diagnosing and resolving deep-rooted UI performance bottlenecks, directly improving usability scores and end-user satisfaction.",
        "Delivered scalable features consistently across sprint cycles as part of a high-performing agile team of 9 engineers.",
      ],
    },
    {
      company: "Wipro Limited · Oracle Cerner",
      title: "Senior Software Engineer, Frontend",
      dateRange: "Dec 2021 – Dec 2025",
      bullets: [
        "Mitigated critical security vulnerabilities across multiple enterprise healthcare projects, achieving 100% adherence to security compliance standards.",
        "Owned key deliverables end-to-end — from investigation through deployment — maintaining high system availability with zero compliance failures during tenure.",
        "Led code reviews that elevated engineering standards and ensured on-time delivery of regulated healthcare software.",
      ],
    },
    {
      company: "Wipro Limited · Thomson Reuters",
      title: "Senior Software Engineer, Frontend",
      dateRange: "Dec 2021 – Dec 2025",
      bullets: [
        "Architected a reusable React component library adopted by 10+ teams, standardizing component patterns and measurably reducing cross-team onboarding friction and code duplication.",
        "Shipped 'Knowledge Hub' — an interactive product training and onboarding experience that accelerated time-to-value for new users and reduced dependency on external support documentation.",
        "Systematically eliminated critical technical debt through targeted debugging and refactoring, improving code readability and application response times.",
      ],
    },
    {
      company: "Reliance Jio",
      title: "Software Engineer, Frontend",
      dateRange: "Aug 2018 – Nov 2021",
      bullets: [
        "Spearheaded full migration of legacy SAP FIORI/OData architecture to a modern React + Redux + Node.js stack, improving frontend flexibility and accelerating developer velocity.",
        "Engineered a comprehensive Order Management UX for dealers and a warehouse application with real-time barcode and serial number scanner integration for product white-listing.",
        "Built a business-critical geo-spatial delivery tracking application integrating real-time map data for live logistical visibility for field associates.",
        "Designed a robust role-based authorization system for multi-server Supply Chain Management (SCM) applications across Jio's logistics network.",
        "Presented UI/UX mockups directly to apex management to drive product roadmap decisions.",
      ],
    },
    {
      company: "Reliance Jio",
      title: "Quality Assurance Engineer",
      dateRange: "Jul 2017 – Jul 2018",
      bullets: [
        "Led a team of 8 QA associates, resolving 80+ critical production issues ahead of launch for Jio Finance and JioSaavn (multimedia streaming) platforms.",
        "Defined end-to-end QA delivery processes for high-traffic Android and iOS media applications.",
      ],
    },
  ],
  education: [
    {
      school: "University of Delhi",
      degree: "Bachelor of Technology — Computer Science",
      dateRange: "Jun 2013 – Jun 2017",
      achievements: ["Graduated with 86.7% aggregate score"],
    },
  ],
};
